### ISSUE TITLE
Check Bioinformatics Markdown

### ISSUE THREAD

**Issue by sr320** [hputnam/Meth_Compare#34] opened 2020-04-04 04:10 UTC
https://github.com/hputnam/Meth_Compare/blob/master/analyses/Meth_Compare_Pipeline.md

Has been updated... It is not perfect as I think we need some confirmation that md5 sums match at each pass through...
But it is logical now and worth a look.

Another goal might be to generate one script does everything... if folks think so, make it an issue.

**Comment by yaaminiv** [comment] 2020-04-06 17:34
@sr320 Can you add checksums for files in `/gscratch/scrubbed/sr320/031520-TG-bs/Mcap_trim/` and `/gscratch/scrubbed/sr320/031520-TG-bs/Pact_trim/` so I can confirm that they are the same output from `/gscratch/scrubbed/strigg/analyses/20200311/RRBS/FASTQC` and `/gscratch/scrubbed/strigg/analyses/20200311/WGBS_MBD/FASTQC`?

**Comment by yaaminiv** [comment] 2020-04-06 17:45
Other than my previous comment, code makes sense to me. Would also need checksums for final output.

**Comment by sr320** [comment] 2020-04-06 17:49
@yaaminiv agree - but how are you confirming? I think we need some code output ie (`sumdiff`?) where anyone can verify - hence https://github.com/hputnam/Meth_Compare/issues/35

**Comment by yaaminiv** [comment] 2020-04-06 17:55
@sr320 I was just going to look at the lists and compare (so not programmatically)...is that okay for now?

**Comment by mgavery** [comment] 2020-04-06 23:27
1. I agree with the comment  about getting the trim transfer info in there. 
2. Although not necessary, it would be nice to have at least commented out in the script which files are made at each step.  For example, does merged_CpG_evidence.cov come from meth_extract?  I just think it would help track all these outputs.

**Comment by sr320** [comment] 2020-04-11 16:06
@yaaminiv and @mgavery New explanation is now integrated.. https://github.com/hputnam/Meth_Compare/blob/master/analyses/Meth_Compare_Pipeline.md#script-explanation-and-distinct-outputs 

Is this what you were thinking or something else?

**Comment by yaaminiv** [comment] 2020-04-13 17:32
> Is this what you were thinking or something else?

Works for what I wanted!

**Comment by mgavery** [comment] 2020-04-13 17:55
works for me too, thanks

**Comment by mgavery** [comment] 2020-04-13 22:07
Should I do MD5 checks for the .cov files that I've transfered to the Rserver?

**Comment by sr320** [comment] 2020-04-13 22:19
Yes

**Comment by mgavery** [comment] 2020-04-16 19:29
Heads up there are 2 cov files for Pact_C1 in the dedup folder.  This was not the case for Mcap and Pact:
srlab@emu:~/GitHub/Meth_Compare/data/gannet.fish.washington.edu/seashell/bu-mox/scrubbed/032320-Pact-C1/Pact_C1/dedup$ ls Meth7*
Meth7_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
Meth7_R1_001_val_1_bismark_bt2_pe.deduplicated..CpG_report.merged_CpG_evidence.cov

**Closed as completed** 2020-04-20 15:51 UTC
