### ISSUE TITLE
Create Corr Plots with new data

### ISSUE THREAD

**Issue by sr320** [hputnam/Meth_Compare#22] opened 2020-03-23 22:08 UTC
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Mcap_tg/dedup/Meth10_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Mcap_tg/dedup/Meth11_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Mcap_tg/dedup/Meth12_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Mcap_tg/nodedup/Meth13_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Mcap_tg/nodedup/Meth14_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Mcap_tg/nodedup/Meth15_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Mcap_tg/dedup/Meth16_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Mcap_tg/dedup/Meth17_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Mcap_tg/dedup/Meth18_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

---
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Pact_tg/dedup/Meth1_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Pact_tg/dedup/Meth2_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Pact_tg/dedup/Meth3_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Pact_tg/nodedup/Meth4_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- (5 and 6) are missing
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Pact_tg/dedup/Meth7_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Pact_tg/dedup/Meth8_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov
- https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Pact_tg/dedup/Meth9_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

**Comment by sr320** [comment] 2020-03-26 01:15
@mgavery created new corr plots @ https://github.com/hputnam/Meth_Compare/tree/master/analyses

**Comment by hputnam** [comment] 2020-03-26 21:06
@mgavery could you also run the Pact plots and the SymC1 plots?

**Comment by sr320** [comment] 2020-03-27 16:15
@sr320 provide C1 merged cov

**Comment by sr320** [comment] 2020-03-27 16:16
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/032320-Pact-C1/Pact_C1/

**Comment by mgavery** [comment] 2020-04-03 04:31
@sr320 are Pact 5 and 6 merged cov files still missing?

**Comment by sr320** [comment] 2020-04-03 04:35
No they are available...

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-bs/Pact_tg/nodedup/Meth5_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-bs/Pact_tg/nodedup/Meth6_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

**Comment by mgavery** [comment] 2020-04-03 21:23
Should I use the Meth4.. that is also in that folder?  (versus the one linked above which is in ../gannet.fish.washington.edu/seashell/bu-mox/scrubbed/031520-TG-100g/Pact_tg/nodedup/Meth4_R1_001_val_1_bismark_bt2_pe..CpG_report.merged_CpG_evidence.cov

**Comment by sr320** [comment] 2020-04-04 19:23
should be the same, but as per the issues that came up yesterday I suggest using one in the folder `031520-TG-bs/`

**Comment by mgavery** [comment] 2020-04-15 23:09
I created corr plots for Mcap and Pact (still need to do C1, has this been QC'd?) They are in the Meth_Compare analyses folder.  The extreme differences in number of common loci between species led me to pull some #'s to get at the cause.  It's my current theory that the Mcap WGBS and MBD data are not close to 'saturation' which is why there is relatively little overlap between samples.  I've documented some things here:https://docs.google.com/spreadsheets/d/1SVwIsMS9BlZFzpT1EOM4LGCrtTM1Tyw--goNGfDlE7Y/edit#gid=0 , and I'm happy to discuss.

**Comment by shellywanamaker** [comment] 2020-04-16 02:32
@mgavery I haven't run MD5 check on C1 alignments and am doing it now. Will post as soon as it's done.

Good point about differences in saturation. Now I'm really interested to check genome coverage. 

And good point about Pact MBD methylation possibly coming from homologous C1 sequence. I wonder if we can filter out homologous sequence and recheck the methylation stats

**Comment by shellywanamaker** [comment] 2020-04-16 04:04
@mgavery confirmed C1 alignment files are good (see issue #35 )

**Comment by hputnam** [comment] 2020-04-16 15:19
Genome information to think about for comparisons

P acuta hosts primarily C1
[vidal-dupiol et al 2019.pdf](https://github.com/hputnam/Meth_Compare/files/4488099/vidal-dupiol.et.al.2019.pdf)

Mcap hosts primarily C31/C17 and D1
[shumaker et al 2019.pdf](https://github.com/hputnam/Meth_Compare/files/4488100/shumaker.et.al.2019.pdf)

Sym C1
[liu et al 2018.pdf](https://github.com/hputnam/Meth_Compare/files/4488121/liu.et.al.2018.pdf)

**Closed as completed** 2020-04-20 15:53 UTC
